### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ChristiaanWewer** [Stanford-ILIAD/PantheonRL#11]
Dear,
I see you have a very nice MARL library for RL.
Currently I am reviewing (MA)RL libraries and I can't find a separate documentation website. Is this true? Maybe I overlook it somewhere.
However the GitHub readme suggests there is one.
Hope you can guide me into the right direction!
Best,
Chris

**Comment by bsarkar321** [comment]
Hi! We currently do not have a separate documentation website. The "documentation" in the readme refers to the detailed pydoc-compatible documentation for our classes and functions within the source code. In particular, the classes and functions in pantheonrl/common detail the interface and assumptions that we make.

**Comment by ChristiaanWewer** [comment]
Perfect, thank you!
