### ISSUE TITLE
AssertionError happended when run example with OvercookedMultiEnv-v0

### ISSUE THREAD

**Issue by momo-xiaoyi** [Stanford-ILIAD/PantheonRL#3]
AssertionError: The observation returned by the `reset()` method is not contained with the observation space (Box(0.0, 20.0, (62,), float32))

**Comment by yanxue7** [comment]
I also encountered this error, excuse me, @momo-xiaoyi did you solve it?

**Comment by momo-xiaoyi** [comment]
change your gym version. this problem can be sloved.

**Comment by momo-xiaoyi** [comment]
gym                          0.21.0

**Comment by yanxue7** [comment]
Thanks! I have solved this problem!
